version: '3'

tasks:
  default:
    desc: Transpile the CDK8s application to Kubernetes manifests
    cmds:
      - deploy

  synth:
    desc: Synthesize the CDK8s application to Kubernetes manifests
    cmds:
      - devcontainer up
      - devcontainer exec cdk8s synth

  deploy:
    desc: Deploy the synthesized Kubernetes manifest(s)
    prompt: Are you sure you want to deploy?
    deps:
      - synth
    cmds:
      - kubectl apply -f dist