# Alpha Vantage API key
#
# TODO: Migrate the API key to cloud provider secret manager or SOPs
api_key: REPLACE_ME

# Name of the environment where the application is deployed
environment: dev

# Name of the container image to deploy
image: 'us-west1-docker.pkg.dev/cloudy-sunday/ticker/ticker:latest'

# Kubernetes resource limits and requests
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

# Name of the application
name: ticker

# Name of the Kubernetes namespace to deploy the application
namespace: ticker

# Number of days to retrieve stock time series data
number_of_days: 3

# Number of desired replicas of the application
replicas: 1

service:
  # Name of the Kubernetes service
  name: ticker

  # Port number of the service
  port: 8080

# Symbol of the stock to operate on
symbol: MSFT
